apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ss7hd2qkr-nodejs 
  janus-idp.io/tekton: ss7hd2qkr-nodejs
  backstage.io/kubernetes-id: ss7hd2qkr-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ss7hd2qkr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml