apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ss7hd2qkr-nodejs
  janus-idp.io/tekton: ss7hd2qkr-nodejs
  backstage.io/kubernetes-id: ss7hd2qkr-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ss7hd2qkr-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
